info:
  microservice: offers
---
spring:
  profiles: default

server:
  port: 9002
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
