
info:
  microservice: products
---
spring:
  profiles: docker
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

service:
  information: default instance only for development purpose
