
info:
  microservice: products
---
spring:
  profiles: default

server:
  port: 9001
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  

information: default instance only for development purpose
